### ISSUE TITLE
ECONNREFUSED y Ayuda con DB

### ISSUE THREAD

**Issue by D0N-B0T** [luiscruzga/offersChile#2]
Hola, estoy obteniendo el siguiente error:

```

PS C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile> npm start

> offerschile@1.0.0 start
> node ./src/index.js --max-old-space-size=8000

[bot.plugin] loaded 'regExpMessage' plugin
[bot.plugin] loaded 'shortReply' plugin
[bot.plugin] loaded 'regExpMessage' plugin
[bot.info] bot started
C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\connection.js:825
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at Connection.openUri (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\connection.js:825:32)
    at C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\index.js:417:10
    at C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\index.js:1270:10)
    at Mongoose.connect (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongoose\lib\index.js:416:20)
    at Object.<anonymous> (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\src\index.js:94:12)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        address: 'localhost:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 12201553,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED ::1:27017
            at connectionFailureError (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongodb\lib\cmap\connect.js:387:20)
            at Socket.<anonymous> (C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile\node_modules\mongodb\lib\cmap\connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ECONNREFUSED ::1:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
            errno: -4078,
            code: 'ECONNREFUSED',
            syscall: 'connect',
            address: '::1',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
PS C:\Users\xxxx\OneDrive\Documentos\proyectos\ofertas\offersChile> 
```

Eso basicamente, lo otro, no me quedo claro el tema de la db, se crea sola?

**Comment by D0N-B0T** [comment]
logré avanzar y ahora estoy teniendo problemas con tablas que no existen. Me gustaria saber si existe alguna forma para crear todo lo necesario, un schema o algo 

ocf_get_products_to_report no existe.

**Comment by D0N-B0T** [comment]
hay otro problema: 

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

```

y en pg.js

```

const PGConnect = async () => {
  client = new Client({
    host: process.env.PG_HOST,
    port: process.env.PG_PORT,
    database: process.env.PG_DB,
    user: process.env.PG_USER,
    password: process.env.PG_PASSWORD,
  })
  console.log('PG connecting');
  await client.connect(); // aqui esta el problema.
  console.log('PG connected');
  return client;
}

```

mi .env está perfecto.


mas problemas:
category.js
`  const dom = await getDataUrl(STORES[storeKey].baseUrl);
`
no está pasando.


Igual es todo mi culpa y no estoy haciendo algo ,lo que es probable. Pero no se que será.
